@echo off
set MATLAB=C:\Program Files\MATLAB\R2018a
"%MATLAB%\bin\win64\gmake" -f PassVeh7DOF.mk  GENERATE_ASAP2=0 EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 TMW_EXTMODE_TESTING=0 OPTS="-DSLMSG_ALLOW_SYSTEM_ALLOC -DMATLAB_MEX_FILE"
